
services:
  dev-conatiner:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    # ports:
    #   - "8080:8080"
    environment:
      - DOCKER_HOST=host.docker.internal
      - DOCKER_TLS_CERTDIR=/certs

  # Add additional services here
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
